version: '3.5'

services:

  watchdog:
    build:
      context: ./Watchdog
    privileged: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${WATCHDOG_EXPOSED_PORT}:80"     
    environment:
      - WORKER_GPU_COUNT=${WORKER_GPU_COUNT}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]     

  bitcrack-client-00:
    image: ogaland/bitcoin-puzzle-bitcrack:cc_86
    #image: bitcoin-puzzle-bitcrack:cc_86
    env_file:
      - .env.gpu.00
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']                # card number to use by this container (1 card allowed, add more workers if you have several cards)
            capabilities: [gpu]    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.173.0/24


